### ISSUE TITLE
RangeError [ERR_OUT_OF_RANGE]: The value of "byteLength" is out of range. It must be >= 1 and <= 6. Received 8

### ISSUE THREAD

**Issue by moyix** [paulsc/onepass#1]
I'm trying to use onepass with node v11.7.0 on Linux. I think I've got all the necessary dependencies installed, but after typing in my master password I get this traceback:

```
moyix@elena:~/git/onepass$ node 1pass
info: Unlocking vault...
Password: 
internal/buffer.js:58
  throw new ERR_OUT_OF_RANGE(type || 'offset',
  ^

RangeError [ERR_OUT_OF_RANGE]: The value of "byteLength" is out of range. It must be >= 1 and <= 6. Received 8
    at boundsError (internal/buffer.js:58:9)
    at Buffer.readUIntLE (internal/buffer.js:80:3)
    at decryptOpdata (/home/moyix/git/onepass/opvault.js:110:34)
    at decryptMainKeys (/home/moyix/git/onepass/opvault.js:156:21)
    at Object.exports.unlockKeychain (/home/moyix/git/onepass/opvault.js:183:16)
    at startDaemon (/home/moyix/git/onepass/1pass.js:18:13)
    at Object.<anonymous> (/home/moyix/git/onepass/1pass.js:14:5)
    at Module._compile (internal/modules/cjs/loader.js:721:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:732:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
```

From a bit of googling, it seems like this might be related to a change in how flexible Node is about dealing with 64-bit integers, and might be fixable with this support for BigInts in the Buffer API:

https://github.com/no2chem/bigint-buffer

(I think there may be plans to add this support into the core Buffer API at some point, but I don't think it's in there yet)

**Comment by paulsc** [comment]
I see. If you end up fixing it, can you submit a PR ? I'm not actively using this anymore. 

Thanks

**Comment by moyix** [comment]
I ended up fixing the immediate problem but ran into a different one. I've since switched over to a different opvault library.

**Comment by deepflame** [comment]
Having a similar issue with Node v10.16.0 on Ubuntu.

```
info: Unlocking vault...
Password: 
internal/buffer.js:49
  throw new ERR_OUT_OF_RANGE(type || 'offset',
  ^

RangeError [ERR_OUT_OF_RANGE]: The value of "byteLength" is out of range. It must be >= 1 and <= 6. Received 8
    at boundsError (internal/buffer.js:49:9)
    at Buffer.readUIntLE (internal/buffer.js:69:3)
    at decryptOpdata (/home/aboehrnsen/Developer/github/paulsc/onepass/opvault.js:111:32)
```

@moyix which library did you end up using?

**Comment by paulsc** [comment]
A bit late, but eventually this is fixed now :)
