### ISSUE TITLE
opdatabin.readBigUInt64LE is not a function

### ISSUE THREAD

**Issue by StormCh** [paulsc/onepass#3]
info: Unlocking vault...
Password: 
/home/christian/Schreibtisch/onepass-master/opvault.js:112
    var plaintextlen = Number(opdatabin.readBigUInt64LE(8));
                                        ^

TypeError: opdatabin.readBigUInt64LE is not a function
    at decryptOpdata (/home/christian/Schreibtisch/onepass-master/opvault.js:112:41)
    at decryptMainKeys (/home/christian/Schreibtisch/onepass-master/opvault.js:158:21)
    at Object.exports.unlockKeychain (/home/christian/Schreibtisch/onepass-master/opvault.js:192:16)
    at startDaemon (/home/christian/Schreibtisch/onepass-master/onepass.js:23:13)
    at Object.<anonymous> (/home/christian/Schreibtisch/onepass-master/onepass.js:19:5)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)

**Comment by paulsc** [comment]
You're probably running an old node version. Try upgrading.
